package com.rawahacoder.foreigncurrencyexchangekmp.domain.model

import foreigncurrencyexchangekmp.composeapp.generated.resources.Res
import foreigncurrencyexchangekmp.composeapp.generated.resources.*
import org.jetbrains.compose.resources.DrawableResource
import org.jetbrains.compose.resources.painterResource



enum class CurrencyKey(val countryName: String, val flagCountry: DrawableResource) {
    AFN(countryName = "Afghanistan", flagCountry = Res.drawable.af),
    ALB(countryName = "Albania", flagCountry = Res.drawable.al),
    DZD(countryName = "Algeria", flagCountry = Res.drawable.dz),
    ANR(countryName = "Andorra", flagCountry = Res.drawable.ad),
    AOA(countryName = "Angola", flagCountry = Res.drawable.ao),
    XCD(countryName = "Antigua and Barbuda", flagCountry = Res.drawable.ag),
    ARS(countryName = "Argentina", flagCountry = Res.drawable.ar),
    AMD(countryName = "Armenia", flagCountry = Res.drawable.am),
    AUD(countryName = "Australia", flagCountry = Res.drawable.au),
    AST(countryName = "Austria", flagCountry = Res.drawable.at),
    AZN(countryName = "Azerbaijan", flagCountry = Res.drawable.az),

    BSD(countryName = "Bahamas, The", flagCountry = Res.drawable.bs),
    BHD(countryName = "Bahrain", flagCountry = Res.drawable.bh),
    BDT(countryName = "Bangladesh", flagCountry = Res.drawable.bd),
    BBD(countryName = "Barbados", flagCountry = Res.drawable.bb),
    BYN(countryName = "Belarus", flagCountry = Res.drawable.byn),
    BLG(countryName = "Belgium", flagCountry = Res.drawable.be),
    BZD(countryName = "Belize", flagCountry = Res.drawable.bz),
    BNN(countryName = "Benin (Dahomey)", flagCountry = Res.drawable.bj),
    BOB(countryName = "Bolivia", flagCountry = Res.drawable.bo),
    BAH(countryName = "Bosnia and Herzegovina", flagCountry = Res.drawable.ba),
    BWP(countryName = "Botswana", flagCountry = Res.drawable.bw),
    BRL(countryName = "Brazil", flagCountry = Res.drawable.br),
    BND(countryName = "Brunei", flagCountry = Res.drawable.bn),

    CVE(countryName = "Cabo Verde", flagCountry = Res.drawable.cv),
    KHR(countryName = "Cambodia", flagCountry = Res.drawable.kh),
    CMR(countryName = "Cameroon", flagCountry = Res.drawable.cm),
    CAD(countryName = "Canada", flagCountry = Res.drawable.ca),
    KYD(countryName = "Cayman Islands, The", flagCountry = Res.drawable.ky),
    CAR(countryName = "Central African Republic", flagCountry = Res.drawable.cf),

    XAF(countryName = "Chad", flagCountry = Res.drawable.td),
    CLP(countryName = "Chile", flagCountry = Res.drawable.cl),
    CNY(countryName = "China", flagCountry = Res.drawable.cn),
    COP(countryName = "Colombia", flagCountry = Res.drawable.co),
    KMF(countryName = "Comoros", flagCountry = Res.drawable.km),

    NZD(countryName = "Cook Islands", flagCountry = Res.drawable.ck),
    CRC(countryName = "Costa Rica", flagCountry = Res.drawable.cr),
    CDI(countryName = "Cote d’Ivoire (Ivory Coast)", flagCountry = Res.drawable.ci),
    HRK(countryName = "Croatia", flagCountry = Res.drawable.hr),
    CUP(countryName = "Cuba", flagCountry = Res.drawable.cu),
    EUR(countryName = "Cyprus", flagCountry = Res.drawable.cy),
    CZK(countryName = "Czechia", flagCountry = Res.drawable.cz),

    ECD(countryName = "Ecuador", flagCountry = Res.drawable.ec),
    EGP(countryName = "Egypt", flagCountry = Res.drawable.eg),
    ESL(countryName = "El Salvador", flagCountry = Res.drawable.sv),
    EQG(countryName = "Equatorial Guinea", flagCountry = Res.drawable.gq),
    ERN(countryName = "Eritrea", flagCountry = Res.drawable.er),
    ESN(countryName = "Estonia", flagCountry = Res.drawable.ee),
    SZL(countryName = "Eswatini", flagCountry = Res.drawable.sz),
    ETB(countryName = "Ethiopia", flagCountry = Res.drawable.et),

    FJD(countryName = "Fiji", flagCountry = Res.drawable.fj),
    FLN(countryName = "Finland", flagCountry = Res.drawable.fi),
    FRN(countryName = "France", flagCountry = Res.drawable.fr),

    GAB(countryName = "Gabon", flagCountry = Res.drawable.ga),
    GMD(countryName = "Gambia, The", flagCountry = Res.drawable.gm),
    GEL(countryName = "Georgia", flagCountry = Res.drawable.ge),
    GRM(countryName = "Germany", flagCountry = Res.drawable.de),
    GHS(countryName = "Ghana", flagCountry = Res.drawable.gh),

    GRR(countryName = "Greece", flagCountry = Res.drawable.gr),
    GRD(countryName = "Grenada", flagCountry = Res.drawable.gd),
    GTQ(countryName = "Guatemala", flagCountry = Res.drawable.gt),
    GNF(countryName = "Guinea", flagCountry = Res.drawable.gn),
    GBS(countryName = "Guinea-Bissau", flagCountry = Res.drawable.gw),
    GYD(countryName = "Guyana", flagCountry = Res.drawable.gy),

    HTG(countryName = "Haiti", flagCountry = Res.drawable.ht),
    HNL(countryName = "Honduras", flagCountry = Res.drawable.hn),
    HUF(countryName = "Hungary", flagCountry = Res.drawable.hu),
    ICL(countryName = "Iceland", flagCountry = Res.drawable.icl),
    INR(countryName = "India", flagCountry = Res.drawable.inr),
    IDR(countryName = "Indonesia", flagCountry = Res.drawable.id),
    IRR(countryName = "Iran", flagCountry = Res.drawable.ir),
    IQD(countryName = "Iraq", flagCountry = Res.drawable.iq),
    IRL(countryName = "Ireland", flagCountry = Res.drawable.ie),
    ILS(countryName = "Israel", flagCountry = Res.drawable.il),
    ITL(countryName = "Italy", flagCountry = Res.drawable.itl),
    JMD(countryName = "Jamaica", flagCountry = Res.drawable.jm),
    JPY(countryName = "Japan", flagCountry = Res.drawable.jp),
    JOD(countryName = "Jordan", flagCountry = Res.drawable.jo),
    KZT(countryName = "Kazakhstan", flagCountry = Res.drawable.kz),
    KES(countryName = "Kenya", flagCountry = Res.drawable.ke),
    KTB(countryName = "Kiribati", flagCountry = Res.drawable.ki),
    KRW(countryName = "Korea", flagCountry = Res.drawable.kr),
    KSV(countryName = "Kosovo", flagCountry = Res.drawable.xk),
    KWD(countryName = "Kuwait", flagCountry = Res.drawable.kw),
    KGS(countryName = "Kyrgyzstan", flagCountry = Res.drawable.kg),
    LAK(countryName = "Laos", flagCountry = Res.drawable.la),
    LTV(countryName = "Latvia", flagCountry = Res.drawable.lv),
    LBP(countryName = "Lebanon", flagCountry = Res.drawable.lb),
    LSL(countryName = "Lesotho", flagCountry = Res.drawable.ls),
    LRD(countryName = "Liberia", flagCountry = Res.drawable.lr),
    LYD(countryName = "Libya", flagCountry = Res.drawable.ly),
    LCH(countryName = "Liechtenstein", flagCountry = Res.drawable.li),
    LTH(countryName = "Lithuania", flagCountry = Res.drawable.lt),
    LXM(countryName = "Luxembourg", flagCountry = Res.drawable.lu),

    MGA(countryName = "Madagascar", flagCountry = Res.drawable.mg),
    MWK(countryName = "Malawi", flagCountry = Res.drawable.mw),
    MYR(countryName = "Malaysia", flagCountry = Res.drawable.my),
    MVR(countryName = "Maldives", flagCountry = Res.drawable.mv),
    XOF(countryName = "Mali", flagCountry = Res.drawable.ml),
    MLT(countryName = "Malta", flagCountry = Res.drawable.mt),
    USD(countryName = "Marshall Islands", flagCountry = Res.drawable.mh),
    MRU(countryName = "Mauritania", flagCountry = Res.drawable.mr),
    MUR(countryName = "Mauritius", flagCountry = Res.drawable.mu),

    NAD(countryName = "Namibia", flagCountry = Res.drawable.na),
    NRU(countryName = "Nauru", flagCountry = Res.drawable.nr),
    NPR(countryName = "Nepal", flagCountry = Res.drawable.np),
    NLD(countryName = "Netherlands", flagCountry = Res.drawable.nl),
    NIO(countryName = "Nicaragua", flagCountry = Res.drawable.ni),
    NGR(countryName = "Niger", flagCountry = Res.drawable.ne),
    NGN(countryName = "Nigeria", flagCountry = Res.drawable.ng),
    MKD(countryName = "North Macedonia", flagCountry = Res.drawable.mk),
    NOK(countryName = "Norway", flagCountry = Res.drawable.no),
    OMR(countryName = "Oman", flagCountry = Res.drawable.om),
    PKR(countryName = "Pakistan", flagCountry = Res.drawable.pk),
    LLW(countryName = "Palau", flagCountry = Res.drawable.pw),
    PAB(countryName = "Panama", flagCountry = Res.drawable.pa),
    PGK(countryName = "Papua New Guinea", flagCountry = Res.drawable.pg),
    PYG(countryName = "Paraguay", flagCountry = Res.drawable.py),
    PEN(countryName = "Peru", flagCountry = Res.drawable.pe),
    PHP(countryName = "Philippines", flagCountry = Res.drawable.ph),
    PLN(countryName = "Poland", flagCountry = Res.drawable.pl),
    PTR(countryName = "Portugal", flagCountry = Res.drawable.pt),
    QAR(countryName = "Qatar", flagCountry = Res.drawable.qa),
    KRS(countryName = "Republic of Korea (South Korea)", flagCountry = Res.drawable.kr),
    RCG(countryName = "Republic of the Congo", flagCountry = Res.drawable.cg),
    RON(countryName = "Romania", flagCountry = Res.drawable.ro),
    RUB(countryName = "Russia", flagCountry = Res.drawable.ru),
    RWF(countryName = "Rwanda", flagCountry = Res.drawable.rw),
    WST(countryName = "Samoa", flagCountry = Res.drawable.ws),
    SMR(countryName = "San Marino", flagCountry = Res.drawable.sm),
    STN(countryName = "Sao Tome and Principe", flagCountry = Res.drawable.st),
    SAR(countryName = "Saudi Arabia", flagCountry = Res.drawable.sa),
    SNG(countryName = "Senegal", flagCountry = Res.drawable.sn),
    RSD(countryName = "Serbia", flagCountry = Res.drawable.rs),
    SCR(countryName = "Seychelles", flagCountry = Res.drawable.sc),
    SLL(countryName = "Sierra Leone", flagCountry = Res.drawable.sl),
    SGD(countryName = "Singapore", flagCountry = Res.drawable.sg),
    SLK(countryName = "Slovakia", flagCountry = Res.drawable.sk),
    SIL(countryName = "Slovenia", flagCountry = Res.drawable.si),
    SOS(countryName = "Somalia", flagCountry = Res.drawable.so),
    ZAR(countryName = "South Africa", flagCountry = Res.drawable.za),
    SSP(countryName = "South Sudan", flagCountry = Res.drawable.ss),
    SPN(countryName = "Spain", flagCountry = Res.drawable.es),
    LKR(countryName = "Sri Lanka", flagCountry = Res.drawable.lk),
    SDG(countryName = "Sudan", flagCountry = Res.drawable.sd),
    SRD(countryName = "Suriname", flagCountry = Res.drawable.sr),
    SEK(countryName = "Sweden", flagCountry = Res.drawable.se),
    CHF(countryName = "Switzerland", flagCountry = Res.drawable.ch),
    SYP(countryName = "Syria", flagCountry = Res.drawable.sy),
    TJS(countryName = "Tajikistan", flagCountry = Res.drawable.tj),
    TZS(countryName = "Tanzania", flagCountry = Res.drawable.tz),
    THB(countryName = "Thailand", flagCountry = Res.drawable.th),
    TLS(countryName = "Timor-Leste", flagCountry = Res.drawable.tl),
    TGO(countryName = "Togo", flagCountry = Res.drawable.tg),
    TTD(countryName = "Trinidad and Tobago", flagCountry = Res.drawable.tt),
    TND(countryName = "Tunisia", flagCountry = Res.drawable.tn),
    TRY(countryName = "Turkey", flagCountry = Res.drawable.tr),
    TMT(countryName = "Turkmenistan", flagCountry = Res.drawable.tm),
    TVL(countryName = "Tuvalu", flagCountry = Res.drawable.tv),
    UGX(countryName = "Uganda", flagCountry = Res.drawable.ug),
    UAH(countryName = "Ukraine", flagCountry = Res.drawable.ua),
    AED(countryName = "United Arab Emirates", flagCountry = Res.drawable.ae),
    GBP(countryName = "United Kingdom", flagCountry = Res.drawable.gb),
    UYU(countryName = "Uruguay", flagCountry = Res.drawable.uy),
    UZS(countryName = "Uzbekistan", flagCountry = Res.drawable.uz),
    VUV(countryName = "Vanuatu", flagCountry = Res.drawable.vu),
    VES(countryName = "Venezuela", flagCountry = Res.drawable.ve),
    VND(countryName = "Vietnam", flagCountry = Res.drawable.vn),
    YER(countryName = "Yemen", flagCountry = Res.drawable.ye),
    ZMW(countryName = "Zambia", flagCountry = Res.drawable.zm),
    ZWL(countryName = "Zimbabwe", flagCountry = Res.drawable.zw),


}